### ISSUE TITLE
Could not find any NDI device in 20 serial port candidates checked.

### ISSUE THREAD

**Issue by ekmungi** [UCL/scikit-surgerynditracker#30]
Hi,

Thanks to the developers for the work on scikit-surgery platform.

I am having some trouble using this on a Aurora tracker with the control unit that is RS232 port and connected to my computer using a RS232 to USB adapter. The device is registered on the dev list as ttyUSB0, however when initializing the tracker using `tracker = NDITracker(settings_aurora)` it does not find the device. I have already added my user to the dialout group, so that is definitely not the issue.

Any help would be really great. Thanks.

Anant.

**Comment by ekmungi** [comment]
Stupid of me, the computer needed a restart to register the dialout group addition.

**Comment by thompson318** [comment]
Thanks for commenting, I assume you've got it working now. We haven't tested it with an RS232 to usb converter, so would love to know how you get on.
