### ISSUE TITLE
Cannot recognize NDI device on MAC OS

### ISSUE THREAD

**Issue by rwjmoore** [UCL/scikit-surgerynditracker#37]
Hi, 

I am receiving this error when running the NDITracker() code: 

"OSError: Could not find any NDI device in 20 serial port candidates checked. Please check the following:" 

I am using a MacBook Pro with a USB to Thunderbolt3 adapter to connect my MacBook to an NDI Aurora. I am wondering if this code supports such adapters. 

My computer is able to recognize the device via the system_profiler SPUSBDataType command, but it appears that this package cannot.

Any suggestions or comments on this? 

Thanks

**Comment by rwjmoore** [comment]
Can confirm that this is not an adapter issue. 

I am running python 3.7 on both Windows and MAC OS systems. Even on windows this problem persists: 

Here is my code: 

from sksurgerynditracker.nditracker import NDITracker
settings_aurora = {'tracker type':'aurora' }
TRACKER = NDITracker(settings_aurora)

Any help would be greatly appreciated. 

Best

**Comment by thompson318** [comment]
Hello, thanks for getting in touch. My first thought is it's a hardware or driver issue. This happens on Windows when the NDI drivers have not been installed and on Linux when there's a USB permissions problem. I haven't really tried it on a MAC. sksurgerynditracker delegates probing serial ports to the ndicapi library, the ndiSerialProbe function can be found here:
https://github.com/thompson318/ndicapi/blob/master/ndicapi.cxx#L723
Have you installed NDI's own software on your Windows machine? If so can you connect with that?

**Comment by rwjmoore** [comment]
Hi, 

Thanks for the quick response. Part of the issue was in fact the driver that I was using on my Mac. I updated my FTDI driver and I was able to connect to the Aurora using a MATLAB script on my Mac, so I can rule out the issue of the drivers. 

However, I am still receiving the same error as the one described in my first post for both Windows and MacOS, even after installing the drivers on both operating systems.

 Could you describe what the "ports to use" key in the Settings dictionary represents? Is this the serial port on the computer or the number of probes that are attached to the Aurora? 

If you have any other suggestions, they would be much appreciated. 

Thanks

**Comment by thompson318** [comment]
Ports to use just specifies how many serial ports to scan, by default it is 20, so if your Aurora was plugged into serial port 21 (which seems unlikely) it would not be found. You could try setting it higher and see what happens.

**Comment by thompson318** [comment]
What version of the Aurora are you using? I think there are some that connect by ethernet rather than USB?

**Comment by thompson318** [comment]
So far we've only tested it with Auroras connected via USB. If you're connecting via ethernet you'd could try modifying line 123 of nditracker.py to:
self._connect_network(configuration)
and make sure ip address and port are set in the configuration.
https://github.com/UCL/scikit-surgerynditracker/blob/master/sksurgerynditracker/nditracker.py#L123

**Comment by rwjmoore** [comment]
Hi, two things that I noticed. On this line, [https://github.com/UCL/scikit-surgerynditracker/blob/956b07300331b218ebc3007ba621b583fe047780/sksurgerynditracker/nditracker.py#L21](url) it checks for "number of ports to probe", but this is not the advertised dict key in the demo. If I go ahead and configure my NDI tracker object using this "number of ports to probe" as a dictionary key, it throws the following error: 

line 147, in _connect_serial
    for port_no in range(ports_to_probe):
TypeError: 'NoneType' object cannot be interpreted as an integer

This is an easy fix, you just need to change the keys to make sure that when a user inputs a desired number of ports, the .get() function here [https://github.com/UCL/scikit-surgerynditracker/blob/956b07300331b218ebc3007ba621b583fe047780/sksurgerynditracker/nditracker.py#L145](url) gets the right key. 

I am using the Aurora V2, which is communicating via USB. I am able to connect to the Aurora SCU using Pyserial, but this package is still unable to find the Aurora when running: 

from sksurgerynditracker.nditracker import NDITracker
settings_aurora = {'tracker type':'aurora' }
TRACKER = NDITracker(settings_aurora)

Running out of ideas here, but I might have to go into the source code and hardcode it to the correct serial port on my computer. Thanks for the help, and if you think of anything else let me know.

**Comment by thompson318** [comment]
Thanks for pointing that out, I will fix it. I'd love to get to the bottom of what's going on here. It might be helpful if you tried going direct to the ndicapy library. You should be able to run something like this;
`import ndicapy
serial_port = 0 # the integer address of the serial port if you know it
name = ndicapy.ndiDeviceName(serial_port)
print (name)
result = ndicapy.ndiProbe(name)
assert result == ndicapy.NDI_OKAY
`

**Comment by thompson318** [comment]
`import ndicapy`
`serial_port = 0 # the integer address of the serial port if you know it`
`name = ndicapy.ndiDeviceName(serial_port)`
`print (name)`
`result = ndicapy.ndiProbe(name)`
`assert result == ndicapy.NDI_OKAY`

**Comment by rwjmoore** [comment]
I think that the problem lies in the fact that the serial port that my Aurora device is connected to is of the form: "/dev/tty.usbserial-00004014". For example, when listing the available serial ports on my Mac, I get the following. 
<img width="520" alt="Screen Shot 2021-06-14 at 1 23 52 PM" src="https://user-images.githubusercontent.com/56764177/121947869-cb129f00-cd13-11eb-861a-1ddbeac884c9.png">

Note that the the "/dev/cu.usbserial-00004014" is the serial port that is connected to my Aurora device. Iterating through the "integer address of the serial port" from values of -6000 to +6000, I am unable to get the variable "name" in your code above to equal "/dev/tty.usbserial-00004014". This makes me believe that this port cannot be accessed via an integer. 

Might I ask if there were any similar issues on the Mac OS that this package was tested on? As I understand, Mac OS ports are unlike COM ports on Window; they do not have an integer designation.

**Comment by thompson318** [comment]
I've pushed a new version (0.1.12) to pypi that fixes the bug you found above, thank you.

I've also added some tests to see what serial ports we're finding on different platforms and check that we find the same serial ports as pyserial. If you have a look at the test output here [https://github.com/UCL/scikit-surgerynditracker/runs/2838442699?check_suite_focus=true](https://github.com/UCL/scikit-surgerynditracker/runs/2838442699?check_suite_focus=true) (expand the "run tests" tab and look at line 16 and lines 25 to 24) you can see that on the MacOS runner both find the serial port at 
`16: Checking port: /dev/cu.Bluetooth-Incoming-Port ['/dev/cu.Bluetooth-Incoming-Port']`. 
I also checked the code we use to find the serial ports on a Mac [see here](https://github.com/thompson318/ndicapi/blob/2github-actions/ndicapi.cxx#L631) which basically looks for any file starting with "/dev/cu" so it should work for you. 

Lastly I've added a verbose flag, so if you add {'verbose' : True} to your configuration and try running it you should get some output describing what ports have been found and their status. If you're able to download version 0.1.12 and post your output that would be really helpful. Thank you.

**Comment by rwjmoore** [comment]
I installed version (0.1.12) and here is the resulting output when I run the script with "verbose" set to True: 


<img width="721" alt="Screen Shot 2021-06-16 at 9 22 59 AM" src="https://user-images.githubusercontent.com/56764177/122247237-72164880-ce84-11eb-904a-96ded649029b.png">

Seemingly, this method of probing is unable to find the usb port that is connected to my device. Below, I have executed the ls /dev/cu* command in the same environment that I ran the above script. As you can see, "/dev/cu.usbserial-00005014" is visible to this command. 

<img width="558" alt="Screen Shot 2021-06-16 at 9 20 41 AM" src="https://user-images.githubusercontent.com/56764177/122246837-206dbe00-ce84-11eb-931d-1df69fceb83a.png">

I am now wondering if this is some sort of permission issue, where the python script does not have access to this port. However, when I directly input the serial port name into Pyserial's method, ser = serial.Serial('/dev/tty.usbserial-00005014') I am able to receive bytes from my Aurora device

**Comment by thompson318** [comment]
Excellent, I think I understand the problem now. I think this is a bug with the upstream library we use to talk to the NDI, I've raised an issue [there](https://github.com/PlusToolkit/ndicapi/issues/24), it looks to me like it can only cope with 4 serial ports on a mac. 

In the meantime I've re-implemented our code to use pyserial to discover the serial ports, which seems a bit more modern anyway. If you install our new version (scikit-surgerynditracker 0.1.13) it should hopefully just work for you now. Please can you try it and let me know?

Also in version 0.1.13 I've added the option to specify the serial port by name, so if you add {'serial port' : '/dev/cu.usbserial-00005014'} to your configuration you can skip the whole port scanning routine anyway. Again, please give it a try and let me know if it works for you. 

thanks.

**Comment by rwjmoore** [comment]
Fantastic, it works beautifully. Thanks for all of the help. Both methods you listed (manual port selection and without manual port selection) worked for me. 

One final note. I have tried to output the tracking data to quaternions by using the code: 

settings_aurora = {'tracker type':'aurora', 'ports to probe': 20, 'verbose': True,  "use_quaternions": True}
TRACKER = NDITracker(settings_aurora)
port_handles, timestamps, framenumbers, tracking, quality = TRACKER.get_frame()


However, the resulting "tracking" variable is a 4x4 array. Looking through the source code, I am expecting to see a 1x7 dimensional array. Any thoughts on what the issue might be?

**Comment by thompson318** [comment]
That's great, thanks for testing it. 

I think you just need to remove the underscore, it should be {"use quaternions": True}
